<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChampionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionMasteryRepository extends EntityRepository
{
    /**
     * @param Player $player
     * @return ChampionMastery[]
     */
    public function findByPlayer(Player $player)
    {
        $queryBuilder = $this->createQueryBuilder('mastery');
        $queryBuilder->leftJoin('mastery.champion', 'champion')
            ->where('mastery.player = :player')
            ->setParameter('player', $player);
        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }
}
