<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MasteryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasteryRepository extends EntityRepository
{
}
