<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchDetailRepository extends EntityRepository
{
    /**
     * @param $regionId
     * @param $matchId
     * @param Player $player
     * @return MatchDetail|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByRegionMatchIdAndPlayer($regionId, $matchId, Player $player)
    {
        $queryBuilder = $this->createQueryBuilder('matchDetail');
        $queryBuilder->leftJoin('matchDetail.participants', 'participant')
            ->where('matchDetail.region = :region')
            ->setParameter('region', $regionId)
            ->andWhere('matchDetail.matchId = :matchId')
            ->setParameter('matchId', $matchId)
            ->andWhere('participant.player = :player')
            ->setParameter('player', $player)
            ->setMaxResults(1);
        $query = $queryBuilder->getQuery();

        return $query->getOneOrNullResult();
    }
}
