<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipantStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantStatsRepository extends EntityRepository
{
}
