<?php

namespace AppBundle\Entity\ParticipantTimelineData;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipantTimelineDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantTimelineDataRepository extends EntityRepository
{
}
