<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipantFrameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantFrameRepository extends EntityRepository
{
}
