<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    /**
     * @param $regionId
     * @return Player|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findPlayerWithoutMatch($regionId)
    {
        $queryBuilder = $this->createQueryBuilder('player');
        $queryBuilder->leftJoin('player.matchReferences', 'matchReference')
            ->where('matchReference.id IS NULL')
            ->andWhere('player.region = :region')
            ->setParameter('region', $regionId)
            ->orderBy('player.summonerLevel', 'DESC')
            ->addOrderBy('player.revisionDate', 'DESC')
            ->setMaxResults(1);
        $query = $queryBuilder->getQuery();

        return $query->getOneOrNullResult();
    }
}
